apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: garbage-collect-registry
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["list", "get", "create"]
