apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: garbage-collect-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garbage-collect-registry
subjects:
- kind: ServiceAccount
  name: garbage-collect-registry
  namespace: ops

